### PR TITLE
Fix TypeError by checking if duration is not Finite before setting cu…

### LINKED ISSUE #4156: TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-...
## Description

The `duration` can occasionally be `NaN`, which causes an error during seeking.

## Sentry Issue
[OPENVERSE-FRONTEND-102](https://openverse.sentry.io/issues/4293171746/?referrer=github_integration)

```
TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
  at handleSeeked (./src/components/VAudioTrack/VAudioTrack.vue?a086:403:20)
  at seek (./src/components/VAudioTrack/VWaveform.vue?01c7:295:7)
  at handleMouseUp (./src/components/VAudioTrack/VWaveform.vue?01c7:324:7)
...
(6 additional frame(s) were not displayed)
```

## Code to change
https://github.com/WordPress/openverse/blob/0ed4071577d846ff222342e5c296b723f5e7bb7e/frontend/src/components/VAudioTrack/VAudioTrack.vue#L453

## Additional information
This seems to happen only on the full layout. We could add a check if the `duration.value` is a finite number. If not, try to get the `duration` from `localAudio`. If `localAudio` does not have a `duration` set, then probably do nothing.

### PR DESCRIPTION
**Pull request by spran180**
…rrentTime.

## Fixes

Fixes #4156 by @sentry-io

## Description

This pull request resolves the TypeError that occurs when the 'currentTime' property is applied to 'HTMLMediaElement' with a non-finite value. This issue arises when the 'duration' value is 'NaN'.

## Changes
- Added checks to ensure that `duration.value` is a finite number before setting `localAudio.currentTime`.
- If `duration.value` is not a finite number, it checks if `localAudio.duration` is a finite number and uses that instead.
- It logs the warning if neither `duration.value` nor `localAudio.duration` is finite number, and skips the seek operation.

## Checklist

- [x] TypeError is handleSeeked while checking the duration value is finite.
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices] (https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines).
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`./ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`./ov just catalog/generate-docs media-props`
      for the catalog or `./ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/components/VAudioTrack/VAudioTrack.vue [hunk 1]
```diff
@@ -450,7 +450,15 @@ export default defineComponent({
        * runtime checks.
        */
       if (localAudio) {
-        localAudio.currentTime = frac * duration.value
+        if(Number.isFinite(duration.value)){
+          localAudio.currentTime = frac * duration.value
+        }
+        else if(Number.isFinite(localAudio.duration)){
```
Comment (obulat) [inline frontend/src/components/VAudioTrack/VAudioTrack.vue:456]:
```suggestion
        else if (Number.isFinite(localAudio.duration)){
```

File: frontend/src/components/VAudioTrack/VAudioTrack.vue [hunk 2]
```diff
@@ -450,7 +450,15 @@ export default defineComponent({
        * runtime checks.
        */
       if (localAudio) {
-        localAudio.currentTime = frac * duration.value
+        if(Number.isFinite(duration.value)){
```
Comment (obulat) [inline frontend/src/components/VAudioTrack/VAudioTrack.vue:453]:
```suggestion
        if (Number.isFinite(duration.value)){
```

File: frontend/src/components/VAudioTrack/VAudioTrack.vue [hunk 3]
```diff
@@ -450,7 +450,15 @@ export default defineComponent({
...
+          localAudio.currentTime = frac * duration.value
+        }
+        else if(Number.isFinite(localAudio.duration)){
+          localAudio.currentTime = frac * localAudio.duration
+        }
+        else{
```
Comment (obulat) [inline frontend/src/components/VAudioTrack/VAudioTrack.vue:459]:
```suggestion
        else {
```

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for your PR, @spran180 !
There are some linting problems that prevent the rest of the CI from running. Could you run `just lint` command in the top-level folder (or `./ov just lint`, if you used ov script)?
I suspect that the lack of spaces before the brackets are the problems, but there could be something else, too

File: frontend/src/components/VAudioTrack/VAudioTrack.vue [hunk 4]
```diff
@@ -450,7 +450,15 @@ export default defineComponent({
...
       if (localAudio) {
-        localAudio.currentTime = frac * duration.value
+        if (Number.isFinite(duration.value)){
+          localAudio.currentTime = frac * duration.value
+        }
+        else if (Number.isFinite(localAudio.duration)){
+          localAudio.currentTime = frac * localAudio.duration
+        }
+        else {
+          console.warn('Duration is not finite. Skipping seek.')
```
Comment (sarayourfriend) [inline frontend/src/components/VAudioTrack/VAudioTrack.vue:460]: @obulat should this use `warn` imported from `~/utils/logger`?

**Comment by spran180** [comment]
Hi @obulat , I ran the pre-commit checks instead of the `just lint` command since I don't have Docker permissions. 

Screenshot 2024-07-01 223215-copy

Please review and let me know if further changes are needed. Thanks!

File: frontend/src/components/VAudioTrack/VAudioTrack.vue (hunk 4 above)
Comment (spran180) [reply frontend/src/components/VAudioTrack/VAudioTrack.vue:460]: Hi @sarayourfriend,

I noticed that the use `warn` isn't imported from `~/utils/logger`. Should I import it, or do you want me to remove the `warn` usage?

Thanks!

Comment (sarayourfriend) [reply frontend/src/components/VAudioTrack/VAudioTrack.vue:460]: Oops, I mean `~/utils/console`, not `logger`, apologies.

But. it would need to be imported, yes. I just wanted to check with Olga whether it should be used here rather than `console.warn` directly. I don't know whether we specifically want to always log this on the client for some reason, for example, which `~/utils/console` would suppress.

**Comment by sarayourfriend** [comment]
It's curious @spran180, looks like pre-commit skipped the prettier hook, which is the one that fails in CI.

Can you try `pre-commit run --all-files`, if you ran it differently before?

**Comment by spran180** [comment]
Hi @sarayourfriend,

I've addressed the issues you pointed out. I ran `prettier` on the `frontend/src/components/VAudioTrack/VAudioTrack.vue` file and committed the changes. Additionally, I made a few more formatting adjustments where necessary. Everything should be in order now. Please let me know if there are any further changes or checks required.

**Review by sarayourfriend — APPROVED** [review]
LGTM! I suppose it's rather hard to add a test to reproduce this issue, so I'm not too worried about it. Thanks for sorting out the linting @spran180 and for the contribution generally :pray:

**Review by zackkrida — APPROVED** [review]
Thanks, @spran180!

File: frontend/src/components/VAudioTrack/VAudioTrack.vue (hunk 4 above)
Comment (zackkrida) [reply frontend/src/components/VAudioTrack/VAudioTrack.vue]: @obulat can you review this discussion and make an issue if necessary? Thanks!
