### PR TITLE
Centralise frontend error reporting (and suppress unactionable Sentry errors)

### LINKED ISSUE #3468: Avoid `AxiosError` when requesting bad image links
## Description

There is a recurrent error of Axios trying to request an image with a wrong uuid. It has 112 occurrences since first seen on Nov 20, 2023.

```
GET /image/f51977d1-081a-4e9f-afe1-
```

It raises an error with the message: `Request failed with status code 404` .

It is unknown to me what or who stumbles upon this URL, but it consumes part of our Sentry quota, so it should be prevented somehow from triggering a notification.

## Reproduction

Reproduction steps are unknown. 

## Sentry details
https://openverse.sentry.io/share/issue/20761d85362b468190131dcda0463e9f/

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #3468 by @krysal

Superceeds #3721 after rebasing the branch to include #3811.

## Description

Introduces a new plugin to centralise network error handling. This allows us to make large-scale changes to how we handle certain classes of networking errors under certain conditions. To resolve the problems in the issue, this PR ignores the types of errors mentioned there, or sends information about them to a place we can better understand them (Plausible). For many ignored errors, we have other mechanisms to inspect and understand them, like API logs, or Cloudflare traffic analysis.

## Testing Instructions

Confirm the new tests sufficiently verify the behaviour of the plugin.

Run the app locally, and visit a search page. Open your browser dev tools network tab, and navigate to a single result. Find the "Related" request for the result, and block it using your dev tools (in Firefox you right click and "Block this URL" from the context menu). Navigate back to search, reload to clear the pinia cache of the related request, then go back to the same single result page. Confirm that the dev console has a log event for an analytics event, NETWORK_ERROR, and that no Sentry event was sent. You can confirm the sentry events by adding a console log at that line so you can see it in your nuxt dev console.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I'm leaving this as a draft intentionally. I'll work on the Playwright tests we discussed in the original PR tomorrow.

File: frontend/src/plugins/errors.ts [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+    fetchingError.message = error.message
+  }
+
+  return fetchingError
+}
+
+/**
+ * Record network errors using the appropriate tool, as needed,
+ * based on response code, status, and request kind.
+ * @param error - The error to record
```
Comment (obulat) [inline frontend/src/plugins/errors.ts:72]: This docstring needs to be updated.

File: frontend/src/stores/media/related-media.ts [hunk 2]
```diff
@@ -59,9 +58,14 @@ export const useRelatedMediaStore = defineStore("related-media", {
...
-        const errorData = parseFetchingError(error, mediaType, "related", {
-          id,
-        })
+        const errorData = this.$nuxt.$processFetchingError(
+          error,
+          mediaType,
+          "related",
+          {
+            id,
+          }
```
Comment (obulat) [inline frontend/src/stores/media/related-media.ts:67]:
```suggestion
          { id }
```
Nit

File: frontend/src/stores/media/index.ts [hunk 3]
```diff
@@ -499,15 +499,17 @@ export const useMediaStore = defineStore("media", {
...
-        const errorData = parseFetchingError(error, mediaType, "search", {
-          searchTerm: queryParams.q ?? "",
-        })
+        const errorData = this.$nuxt.$processFetchingError(
+          error,
+          mediaType,
+          "search",
+          {
+            searchTerm: queryParams.q ?? "",
+          }
```
Comment (obulat) [inline frontend/src/stores/media/index.ts:508]:
```suggestion
          { searchTerm: queryParams.q ?? "" }
```
Nit: these seem more readable when on a single line

**Review by obulat — APPROVED** [review]
I've tested this PR locally, and it seems to work really well.

File: frontend/src/plugins/errors.ts [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+     * 1. Plausible will already record them as resulting in a 404 page view
+     * 2. The Openverse API 404s on malformed identifiers, so there is no way
+     *    to distinguish between truly not found works and bad requests from
+     *    the client side.
+     * 3. There isn't much we can do other than monitor for an anomalously high
+     *    number of 404 responses from the frontend server that could indicate a frontend
+     *    implementation or configuration error suddenly causing malformed
+     *    identifiers to be used. Neither Sentry nor Plausible are the right tool
+     *    for that task. If the 404s are caused by an API issue, we'd see that in
+     *    API response code monitoring, where we can more easily trace the cause
```
Comment (zackkrida) [inline frontend/src/plugins/errors.ts:99]:
```suggestion
     *    API response code monitoring, where we can more easily trace the cause.
```

File: frontend/src/plugins/errors.ts [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+    context.$sendCustomEvent("NETWORK_ERROR", {
+      requestKind: fetchingError.requestKind,
+      searchType: fetchingError.searchType,
+    })
+  } else {
+    context.$sentry.captureException(originalError, {
+      extra: { fetchingError },
+    })
+  }
+}
```
Comment (zackkrida) [inline frontend/src/plugins/errors.ts:121]: ``
```suggestion
    return
  } 
  
  // Send all other errors to Sentry
  context.$sentry.captureException(originalError, {
    extra: { fetchingError },
  })
}
```

Style nit: perhaps this would make adding future additional cases less error-prone, or avoid confusion if folks think there's some special relationship between the `process.client && fetchingError.code === "ERR_NETWORK"` errors and Sentry specifically.

**Review by zackkrida — APPROVED** [review]
This is really, really nice! Wow. Great code and works perfectly. Unit tests passed locally, failed correctly when modified, and I was able to produce a NETWORK_ERROR analytics event using the instructions. I left a minor typo and code style suggestion but LGTM.

File: frontend/src/plugins/errors.ts (hunk 5 above)
Comment (sarayourfriend) [reply frontend/src/plugins/errors.ts:121]: I went back and forth many times on this, and ultimately found both just as confusing, and went with a coin toss. I'll switch this, as any actual preference is better than my 50/50 non-choice!

**Comment by sarayourfriend** [comment]
I merged this, forgetting that the reason I didn't do so earlier was because of some outstanding minor feedback. Apologies! I am not intentionally disregarding them. If any of those pieces feel critical enough to make issues for, please let me know which ones and I can create the issues @zackkrida @obulat.

Some of them are things ESlint should be able to catch: early return vs `else`? And object/brace formatting.

**Comment by zackkrida** [comment]
Looks fine as-is for me :+1:
