### PR TITLE
Combine related media component using `VMediaCollection.vue`

### LINKED ISSUE #3832: Related audio does not send `relatedTo` prop in analytics
## Description

When you click on a related audio result, analytics event should contain the id of the item this audio is "related to", but it's always set to `null`:

https://github.com/WordPress/openverse/blob/2cffcb9f8da6961e84a00854a3cd472fd0f9dad8/frontend/src/components/VSearchResultsGrid/VAudioResult.vue#L79

## Reproduction

1. Run the app and click on a related audio result.
2. Check the analytics event that's logged in the console.
3. See error: the `relatedTo` is set to `null`

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Extracted from #3785 to make it easier to review.
Fixes #3832 by @obulat

_Note: 428 lines of the 987 added lines are from "tapes" (saved API responses used for tests)_

## Description

We currently have two separate components for related images and related audio that are basically duplicating each other. This PR combines the 2 related components.

A bigger change is the new `VMediaCollection` component (originally introduced in #3785, but split from it to make reviewing simpler).

This component handles displaying the header, grid skeleton if fetching or the media collection if fetched, and the footer with load more button and the external search form, if necessary.

To simplify this component, I used slots for header and footer, and created `wrapper` components (similar to the audio templates) for the related, search and collection results. This PR contains the `VMediaCollection` and the `VRelatedMedia.vue` wrapper component. It does not use footer because the related media does not have load more button (or the external search form).

This PR renames the "old" components  for audio and image grid to minimize the number of changes (`VImageGrid` and `VAudioList` are "old", and `VImageCollection` and `VAudioCollection` are the new ones).

There's also a tiny unrelated change: the loading skeleton for image single result is now centered (using `mx-auto` class).

## Testing Instructions

Select an audio result and click on one of the related audios. You should see the `SELECT_RESULT` event with the `relatedTo` set correctly. The related images/audio should look correct.

Look at the single result pages. The related media section should look and behave correctly.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
I'll review this in the next day! Somehow didn't see that I was on it.

File: frontend/src/components/VSearchResultsGrid/VAudioList.vue
Comment (obulat) [inline frontend/src/components/VSearchResultsGrid/VAudioList.vue:1]: This is the old `VAudioCollection.vue` component.

File: frontend/src/components/VMediaInfo/VRelatedMedia.vue [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+      return q ?? ""
+    })
+
+    const i18n = useI18n()
+
+    const collectionLabel = computed(() => {
+      const key =
+        props.mediaType === "audio"
+          ? "audioDetails.relatedAudios"
+          : "imageDetails.relatedImages"
```
Comment (zackkrida) [inline frontend/src/components/VMediaInfo/VRelatedMedia.vue:91]: Does this impact our line number matching in the `.pot` files? I don't think so, because it's the full strings, but want to confirm.

File: frontend/src/components/VSearchResultsGrid/VAudioCollection.vue [hunk 2]
```diff
@@ -64,23 +54,39 @@ export default defineComponent({
...
+      type: String as PropType<string | null>,
+      default: null,
+    },
   },
-  setup() {
-    const { isVisible: isSnackbarVisible } = useAudioSnackbar()
+  setup(props) {
+    const uiStore = useUiStore()
+
+    const audioTrackSize = computed(() => {
```
Comment (zackkrida) [inline frontend/src/components/VSearchResultsGrid/VAudioCollection.vue:76]:
```suggestion
		// Determine the size of the audio track based on the kind
		// of collection and the current breakpoint.
    const audioTrackSize = computed(() => {
```

Nit: but the nested ternaries are a lot to take in, maybe a comment could help.

**Review by zackkrida — APPROVED** [review]
This is really nice work. The type improvements and tests look good too. I left a minor suggestion and a design question.

File: frontend/src/components/VMediaInfo/VRelatedMedia.vue [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    kind="related"
+    :related-to="relatedTo"
+    :search-term="searchTerm"
+    :aria-label="collectionLabel"
+  >
+    <template #header>
+      <h2
+        id="related-heading"
+        class="heading-6 mb-6"
+        :class="results.type === 'image' ? 'md:heading-5' : 'lg:heading-6'"
```
[the remark this answers is not in the document]
Comment (obulat) [reply frontend/src/components/VMediaInfo/VRelatedMedia.vue:16]: This might not even be for the consistency with Figma. This is what we currently have on the live site, so I used it so that I don't have to also update the snapshots :)

[the remark this answers is not in the document]
Comment (obulat) [reply frontend/src/components/VMediaInfo/VRelatedMedia.vue:16]: I opened a new issue for this to keep track: #3863

File: frontend/src/components/VMediaInfo/VRelatedMedia.vue (hunk 1 above)
Comment (obulat) [reply frontend/src/components/VMediaInfo/VRelatedMedia.vue:91]: I don't know, will need to check. Would the line numbers make the strings fuzzy in GlotPress?

**Review by dhruvkb — APPROVED** [review]
