### PR TITLE
Wrap usage of `useSensitiveMedia` with `computed`

### LINKED ISSUE #2927: `useSensitiveMedia` composable doesn't update when media changes
## Description

The media sensitivity and blurring is not updated when the global media item changes.

## Reproduction

1. Go to staging.openverse.org/preferences and turn on the 3 sensitivity flags (including the `fake_sensitive`)
2. Narrow the screen to mobile width and search for some audio.
3. Play one of the "non-sensitive" audio items so that the global audio player appears. Then, click on one of the audio items that is blurred because it is sensitive.
4. See error: the audio title is not blurred in the global audio player because the composable is still using the first audio item to detect sensitivity. 
Note: it works the other way around, too: if you first play a sensitive item, then all audio titles will be blurred in the global audio player, even if the items are not sensitive.

## Screenshots

Kapture 2023-08-31 at 09 38 51

## Additional context

To fix this, we should pass the media as a `ref` to the `use-sensitive-media` composable.
I set the priority to high because this must be fixed before rolling out the Frontend blurring of sensitive content project.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2927 by @obulat

## Description

This PR wraps usages of the `useSensitiveMedia` composable with `computed` so that the value of `shouldBlur` is updated with the prop `audio` changes.

## Testing Instructions

Try to reproduce the problem in the linked issue. If you are unable to, consider the issue fixed.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue [hunk 1]
```diff
@@ -60,7 +60,9 @@ export default defineComponent({
     },
   },
   setup(props) {
-    const { isHidden: shouldBlur } = useSensitiveMedia(props.audio)
+    const shouldBlur = computed(
+      () => useSensitiveMedia(props.audio).isHidden.value
+    )
```
Comment (sarayourfriend) [inline frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue:65]: Calling `useSensitiveMedia` inside the computed callback could be risky if `useSensitiveMedia` provisions `ref` objects, which it does (`isHidden` itself is a `computed`).

Olga suggested the following fix in the issue:

> To fix this, we should pass the media as a ref to the use-sensitive-media composable.

I think this is the better fix and would require less code overall. To implement the fix, we'd just need to wrap `props` in `toRefs`:

```suggestion
    const { audio } = toRefs(props)
    const { isHidden: shouldBlur } = useSensitiveMedia(audio)
```

As Olga pointed out the issue, the problem with the current implementation is that `props.audio` is getting detached from updates to `props`, so `audio` is no longer reactive. The current implement is identical to destructuring from the raw `props` object, as opposed to using `props.audio` inside the ref. `toRefs` ensures that the new `audio` ref pulled from `toRefs(props)` is updated whenever the reactive `props` object is updated.

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
Left a request for changes to the implementation to avoid issues with creating computeds inside of computeds.

File: frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue (hunk 1 above)
Comment (dhruvkb) [reply frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue:65]: I was under the impression that both solutions were functionally equivalent and had no idea about it being "risky". Could you elaborate on what the risk is and how? Is that related to the memory leak issue we had a while before?

Comment (sarayourfriend) [reply frontend/src/components/VAudioThumbnail/VAudioThumbnail.vue:65]: Yes! The memory leak issue we saw before is exactly it. Each time the computed re-runs, the call to `useSensitiveMedia` provisions the computed refs it uses each time instead of reusing the existing ones, and those don't get garbage collected. It might not be visible on the server side because of how the page renders, but this one would be evident client side.

Here's the PR where we fixed it before: https://github.com/WordPress/openverse-frontend/pull/1747

I can't find the explanation we had for why it happened.

If the other implementation is preferable for some reason, you could always profile it locally and see whether it has the same issue.

**Review by obulat — COMMENTED** [review]
We can use the `unref` to allow for passing `audio` **or** `ref<audio>`.

I think that we only need the ref for global audio, because it's the only element in which the value of `audio` _can change_. For the other audio track components, `audio` stays the same throughout the lifetime of the component.

**Comment by dhruvkb** [comment]
I made the changes and force-pushed 2219a4e (to overwrite d95c8a3), but that doesn't work at all. It needs more investigation.

**Review by sarayourfriend — APPROVED** [review]

**Comment by dhruvkb** [comment]
Yeah, the thumbnail also needs to account for the audio change.
