### PR TITLE
Fix the skip-to-content link reloading the results

### LINKED ISSUE #3940: Using "skip to content" button on search results page clears result counts (staging only)
## Description

During keyboard navigation, using the "skip to content" button on the search page, the page will lose all result counts and say "no results" for all media types.

## Reproduction

1.  Navigate to https://staging.openverse.org
2.  Tab once and select "skip to content"
3. Tab again to enter the search box
4. Type a search term ("galah" for example) and then enter to start the search
5. Allow the page to finish loading the results and confirm that there are results and that the result counts on the page reflect the number of results (for galah, that's >10k images and 8 audio). To do so using keyboard navigation and a screen reader, you can tab to the results list _without selecting skip to content_ and read the result counts.
6. If you tabbed to the results list, tab back to the skip to content button, and select it. If you are on the page without having interacted, tab once and select skip to content.
7. There will now be "no results" in all places that previously had result counts.

## Additional context

This is on staging only right now (I cannot reproduce on `openverse.org` only `staging.openverse.org`), but I am marking as critical because we cannot deploy the frontend with this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #3940 by @sarayourfriend

## Description

This PR converts the skip-to-content link to an `a` anchor link instead of using the `VLink` component because this component links to a hash `#content` URL, and `VLink` introduces unnecessary complexity for it.
To stop the media re-loading when clicking on `skip-to-content`, I added a check for hash in the `search.ts` middleware. We don't update anything in the middleware if the navigation was caused by a hash change.

## Testing Instructions

Try searching for something, and then use <kbd>Tab</kbd> to focus the Skip-to-content button, click on the button to navigate to content. You should not see the media reload or the content links change number of results.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/pages/image/collection.vue [hunk 1]
```diff
@@ -1,5 +1,9 @@
 <template>
-  <div class="p-6 pt-0 lg:p-10 lg:pt-2">
+  <div
+    :id="`#${skipToContentTargetId}`"
```
Comment (zackkrida) [inline frontend/src/pages/image/collection.vue:3]:
```suggestion
    :id="skipToContentTargetId"
```

This fixes the skip to content link on the collection pages :smile:

**Review by zackkrida — APPROVED** [review]
Excellent! There is one thing that is broken but it is a one line fix, so I will pre-approve knowing you will add the fix so we can get this critical bug resolved and unblock staging deployments.
