### PR TITLE
Fix mobile recent searches modal with banners

### LINKED ISSUE #2603: Prevent the header overlapping the main content when the banners are visible and skip-to-content is clicked
## Description

In #2538 we've added simplified skip-to-content links. The problem is that when the users click on the links, the page scrolls under the header. To prevent that, we've added the `scroll-mt-20` class. However, when the banners are visible, the header area becomes taller, and the content is still hidden beneath the header when you click on the "skip-to-content" link.

## Solution
We should use a `--header-height` css variable that is computed in the layouts to account for all of the banners and the header. This CSS variable should be used to set the `scroll-margin` of the `skip-to-content` link.

## Additional information
Originally noted in 2538 by @sarayourfriend :
> LGTM. The changes to prevent the header overlap work when there are no banners. With one banner at least part of the word is still visible, so while not ideal, there's the visual queue to scroll up a little to see the heading. Ideally we'd be able to correct the amount of margin for the number of banners present. A CSS custom property that gets updated by the banner components when they render is the only way I can think to do that, but it would need to be a manual approach rather than using the tailwind utilities for this.

_Originally posted by @sarayourfriend in https://github.com/WordPress/openverse/pull/2538#pullrequestreview-1521222386_

### LINKED ISSUE #4729: Input is not visible when recent searches are open on mobile and banners are visible
## Description

The recent searches modal hides part of the search bar when a banner is present.

## Reproduction

1. Clear `ui` cookies in your browser to make the analytics banner appear.
2. Go to https://openverse.org/search?q=cat
3. Click on the search bar to open the recent searches modal.
4. See error: more than half of the search bar is hidden.

## Screenshots

Screenshot 2024-08-08 at 7 32 07 AM

### PR DESCRIPTION
**Pull request by obulat**
_Marked as critical because this issue does not allow search on mobile when the banner is not dismissed_

## Fixes

Fixes #4729 by @obulat

## Description

This PR adds a `--header-height` CSS variable that is then used to compute the height of the modal backdrop, and the modal offset from the top to make sure that any banners inside the header element are taken into account.

I tried to also fix #2603 in this PR, but because clicking "Skip to content" _navigates_ to a `#content` hash route, it requires a [router options](https://nuxt.com/docs/guide/recipes/custom-routing#router-options) [scroll behavior changes](https://router.vuejs.org/guide/advanced/scroll-behavior).

## Testing Instructions

1. Clear the `ui` cookies in your browser, or use _incognito_ mode.
2. Use the _mobile, narrow_ screen width.
3. Run the app and go to `http://localhost:8443/search?q=cat` or `http://localhost:8443/ru/search?q=cat`
4. You should see a banner or two banners at the top.
5. Click on the search bar. The recent searches modal should open, and it should not hide any part of the search bar.

Now do the same in production: on https://openverse.org/ru/search?q=cat you should see 2 banners, and the recent searches modal hides the bottom banner as well as the search bar.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/layouts/search-layout.vue [hunk 1]
```diff
@@ -54,6 +55,14 @@ watch(mainPageY, (y) => {
...
 onMounted(() => {
   mainPageElement.value = document.getElementById("main-page")
+  headerElement.value = document.getElementsByClassName(
+    "header-el"
+  )[0] as HTMLElement
+})
+
+const { height } = useElementSize(headerElement)
+watch(height, (height) => {
+  uiStore.setHeaderHeight(height)
```
Comment (sarayourfriend) [inline frontend/src/layouts/search-layout.vue:65]: This is miserable :disappointed: I wish there was another easy way to fix this, but we've put ourselves into such a hole by managing the layout of these elements with JavaScript instead of CSS :face_with_diagonal_mouth: 

At the very least, it would be nice to clean this up in a fast-follow by creating a component to encapsulate this behaviour instead of selecting on the classname in a random part of the app. 

Not blocking this due to criticality.

File: frontend/test/playwright/e2e/recent-searches.spec.ts [hunk 2]
```diff
@@ -100,53 +133,76 @@ breakpoints.describeMobileXsAndDesktop(({ breakpoint }) => {
     const recentSearchesText = await getRecentSearchesText(page)
     expect(recentSearchesText).toContain(noRecentLabel)
   })
+})
 
-  test("can open recent searches with keyboard", async ({ page }) => {
-    await executeSearches(page)
-    await tabToSearchbar(page)
-    await page.keyboard.press("ArrowDown")
+breakpoints.describeMobileXsAndDesktop(({ breakpoint }) => {
```
Comment (sarayourfriend) [inline frontend/test/playwright/e2e/recent-searches.spec.ts:138]: In a fast-follow PR, we should add a test that ensures the search box can be clicked when the recent searches is open at each breakpoint.

**Review by sarayourfriend — APPROVED** [review]
LGTM tested well locally. I have two comments that, were this PR not critical, I would block on. Instead, they should be done in a follow-up PR.
