### PR TITLE
Handle global audio play errors

### LINKED ISSUE #3487: `NotSupportedError` when trying to play audio
## Description 

Strangely, the stack trace that Sentry shows does not correspond with the current source code, but this continues to happen until 2 days ago.

Screenshot 2023-12-07 at 17-33-52 NotSupportedError The operation is not supported  The operation is not supported  — openverse — openverse-frontend

Suspicious URL: https://openverse.sentry.io/share/issue/dc034d52f859473f97213c3e3319cdd5/

```
NotSupportedError: The operation is not supported.
  at <object>.handleToggle (./src/components/VAudioTrack/VGlobalAudioTrack.vue?2f23:159:47)
  at <object>.handleClick (./src/components/VAudioTrack/VAudioControl.vue?0fe5:122:7)
...
(3 additional frame(s) were not displayed)
```

## Sentry Issue
[OPENVERSE-FRONTEND-1GT](https://openverse.sentry.io/share/issue/dc034d52f859473f97213c3e3319cdd5/)

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #3487 by @sentry-io

## Description

This PR creates a `playActiveAudio` function within the active media store to play the audio and correctly handle play errors for both the `VAudioTrack`'s  and the `VGlobalAudioTrack`'s audio elements.

I'm not sure about the location of this function. At first, I wanted to put it in a separate file, something like `utils/audio.ts`. However, this function needs access to set the store's message and also needs to be able to send a Sentry message. That's why I put it inside the active media store, and added the html audio element as  a parameter. Suggestions on better placement welcome!

I also fixed the error message showing the key instead of the string in the global audio player.

## Testing Instructions

Use an iphone or an iphone simulator.
Run the app using `just frontend/run dev`
Search for audios and select `OGG` in the `Extensions` filters.
Play an audio. You should see "This audio format is not supported by your browser" instead of "err_unsupported" in the waveform area.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/components/VAudioTrack/VGlobalAudioTrack.vue [hunk 1]
```diff
@@ -157,7 +158,7 @@ export default defineComponent({
         )
 
         currentTime.value = audio.currentTime
-        if (audio.duration && !isNaN(audio.duration)) {
+        if (audio.duration && !Number.isNaN(audio.duration)) {
```
Comment (obulat) [inline frontend/src/components/VAudioTrack/VGlobalAudioTrack.vue:161]:
```suggestion
        if (audio.duration && !isNaN(audio.duration)) {
```

**Review by AetherUnbound — APPROVED** [review]
I can't give any input on the placement within the code, but I tested this locally with my neighbor's iPhone and confirmed it failed as expected!

image

**Review by zackkrida — APPROVED** [review]
This is a very nice approach and super clean PR. Well done!
