### PR TITLE
Fix global audio player layout

### LINKED ISSUE #913: Global audio player is broken
## Problem

The global audio player renders incorrectly on mobile. The track itself appears missing.
We also need to make sure the close button works correctly.

CleanShot 2023-03-14 at 11 26 41

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #913 by @zackkrida

## Description

This PR adds one more grid row to the `content-layout` for the global audio player. Its height is set to auto, so it is 0 when the player is closed, and full height when it's open.

It also adds the visual regression test and activates the e2e test for the global audio player.

## Testing Instructions

Run the app using `just frontend/run dev` and go to `localhost:8443`. Make sure that the screen is on mobile width. Search for audio, and play one of the results. The global audio player should open in the bottom of the screen. The audio should change if you click on a different result, and it should keep playing if you open the details page.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: frontend/src/components/VGlobalAudioSection/VGlobalAudioSection.vue [hunk 1]
```diff
@@ -147,3 +147,8 @@ export default defineComponent({
   },
 })
 </script>
+<style>
```
Comment (dhruvkb) [inline frontend/src/components/VGlobalAudioSection/VGlobalAudioSection.vue:150]: I don't know if this is the style guide or a personal preference but there should be a blank line between `</script>` and `<style>`.

File: frontend/src/layouts/content-layout.vue [hunk 2]
```diff
@@ -167,7 +167,7 @@ export default defineComponent({
   width: var(--filter-sidebar-width);
 }
 .app {
-  grid-template-areas: "header header" "main main";
+  grid-template-areas: "header header" "main main" "global-audio global-audio";
```
Comment (dhruvkb) [inline frontend/src/layouts/content-layout.vue:170]: Since the grid only has one column when `isSidebarVisible` is `false` (see L10), this can be simplified.

```suggestion
  grid-template-areas: "header" "main" "global-audio";
```

**Review by dhruvkb — APPROVED** [review]
LGTM, appreciate the added e2e and VR tests.

File: frontend/src/layouts/content-layout.vue (hunk 2 above)
Comment (obulat) [reply frontend/src/layouts/content-layout.vue:170]: Nice, I haven't thought about that 🤦 Thanks!

File: frontend/src/components/VGlobalAudioSection/VGlobalAudioSection.vue (hunk 1 above)
Comment (obulat) [inline frontend/src/components/VGlobalAudioSection/VGlobalAudioSection.vue:150]:
```suggestion

<style>
```

**Review by zackkrida — APPROVED** [review]
The layout is fixed, but it's rendered somewhat useless by the fact that the "close" button is broken. I'm okay with us fixing that in a fast follow PR. Thanks for the changes here!

**Comment by obulat** [comment]
> The layout is fixed, but it's rendered somewhat useless by the fact that the "close" button is broken. I'm okay with us fixing that in a fast follow PR. Thanks for the changes here!

I meant to file a new issue for that. You _can_ close the player if you stop the audio. It has something to do with the yellow progress bar.
