### PR TITLE
Make `load_sample_data` more resilient

### LINKED ISSUE #2359: `TableIndexer` has no attribute `load_test_data`
## Description

#2322 removed the `load_test_data` method from `TableIndexer`. This will be fixed in a PR I will put up soon but a separate critical issue needs to evaluate why this didn't cause CI to fail. With this error locally, all local indexes end up with 0 results.

## Reproduction

1.  Checkout `main` and run `just down -v`, `just api/up` then `just api/init`. See that `LOAD_TEST_DATA` actions both fail, but the rest of init proceeds. Check your Elasticsearch cluster locally and see that there are zero documents.

```
$ curl http://localhost:50292/_cat/indices/image\?v\=true
health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   image-init 0jnENyXiTrCy-NeNWB6Siw  18   0          0            0      3.6kb          3.6kb
```

## Environment

- Device: 
- OS: 
- Browser: 
- Version: 
- Other info:

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Addresses #2359 by @sarayourfriend

## Description

This PR makes these changes:
- ensures that invalid API calls to the ingestion server using cURL fail locally for non-2xx response codes.
- checks for sample data to be loaded in SQL after issuing `DELETE` and `\copy` to the database.

This PR does not rewrite the script in a different language, like Python, for two reasons:
- It has been tried before (WordPress/openvere-api#830) but it was turned down as it was too much rewriting for the little value gained.
- The current structure of the script is largely a collection of `just` recipe invocations. Switching to Python will not improve any inherent fragility in those recipes.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: load_sample_data.sh [hunk 1]
```diff
@@ -12,16 +12,28 @@ DB_SERVICE_NAME="${DB_SERVICE_NAME:-db}"
...
+  if [ "$COUNT" -ne 5000 ]; then
+    echo "Error: table $1 count differs from expected."
+    exit 1
+  fi
+}
+
 load_sample_data "image"
+verify_loaded_data "image"
 load_sample_data "audio"
+verify_loaded_data "image"
```
Comment (zackkrida) [inline load_sample_data.sh:36]:
```suggestion
verify_loaded_data "audio"
```

**Review by zackkrida — APPROVED** [review]
One major error resulting from a typo, but it's such a quick fix that I'll commit it and give this the approval. 

Edit: typo fixed in b53e266d3ce5c6b95ebce04e9e5678d811d04c26

File: ingestion_server/justfile [hunk 2]
```diff
@@ -62,12 +62,17 @@ wait-up: up
...
       -d '{{ data }}' \
-      -w "\n" \
-      'http://{{ host }}/task'
+      -o /dev/stderr \
+      -w "%{http_code}" \
+      'http://{{ host }}/task'); \
+    if [ $STATUS_CODE -lt 200 ] || [ $STATUS_CODE -ge 300 ]; then \
+      echo "Status: $STATUS_CODE"; \
+      exit 1; \
+    fi
```
Comment (sarayourfriend) [inline ingestion_server/justfile:75]: I was surprised by this because I assumed cURL supported some kind of method for changing the exit code if the status was bad. It turns out there's a relatively new feature (2021) that does this: [`--fail-with-body`](https://curl.se/docs/manpage.html#--fail-with-body). It has the added benefit of still printing the response body with the failure without needing to add any more flags (or checks).

**Review by sarayourfriend — APPROVED** [review]
This is a nice change, but I don't think it resolves the linked issue. Calls to the ingestion server return a task ID. If that task fails the script will continue on without issue. The call to ingest the test data, for example, only checks if the index is created afterwards before moving on, not that the task actually finished or succeeded.

The reason to convert to Python is that it would be way easier to parse the request body for the task ID and make repeated requests to the task endpoint of the ingestion server. [The PR you mentioned](https://github.com/WordPress/openverse-api/pull/830) didn't do that either, to be fair, and I think overcomplicated things by reusing the just recipes and adding new functionality, rather than converting the script as is. I don't think that previous PR is necessarily a good comparison or an indication that re-writing to Python doesn't make certain aspects of it easier. The linked PR did a _lot_ more than re-write to Python and add checks on the task IDs.

Anyway, this is a change that we should merge, but I don't think it fully resolves the issue as the tasks can still fail and the script would go on anyway.

File: ingestion_server/justfile (hunk 2 above)
Comment (dhruvkb) [reply ingestion_server/justfile:75]: I didn't use that because a lot of us are developing on macOS and might have an older version of cURL built-in. Installing a new version of cURL is technically an option but I experienced SSL issues when I last did that and I didn't want to force an additional system-level dependency.

**Comment by dhruvkb** [comment]
I changed "Fixes ..." to "Addresses ..." to leave the linked issue open after merging this PR.

File: ingestion_server/justfile (hunk 2 above)
Comment (sarayourfriend) [reply ingestion_server/justfile:75]: Ah, TIL that macOS is on an old version :+1:

Comment (dhruvkb) [reply ingestion_server/justfile:75]: Not only cURL, macOS comes bundled with plenty of old utils. 

I also had problems with Git when I tried to use some new feature (can't recall what it was), didn't have it, installed Git with Brew which then refused to work with SSH proto. It was a whole thing to reset everything 😢.
